/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cognito_identity_pool_id": "us-west-1:bf08bff6-9f73-4c72-8877-5adfc1dcb0c2",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_CMDP3jkJf",
    "aws_user_pools_web_client_id": "4favc9o5ob4hqkq4ic1pmphapo",
    "oauth": {
        "domain": "promocam0e156cba-0e156cba-dev.auth.us-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://main.d1yvgfozktnyg2.amplifyapp.com/,http://localhost:4200/",
        "redirectSignOut": "https://main.d1yvgfozktnyg2.amplifyapp.com/,http://localhost:4200/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
